# Generated by Django 4.1.13 on 2024-02-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlabapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=50, unique=True)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('committed_date', models.DateTimeField()),
            ],
        ),
    ]
